// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2-1.proto

package proto_mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Resource_TYPE int32

const (
	Resource_UNSPECIFIED Resource_TYPE = 0
	Resource_TOOL        Resource_TYPE = 1
	Resource_MATERIAL    Resource_TYPE = 2
)

var Resource_TYPE_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "TOOL",
	2: "MATERIAL",
}

var Resource_TYPE_value = map[string]int32{
	"UNSPECIFIED": 0,
	"TOOL":        1,
	"MATERIAL":    2,
}

func (x Resource_TYPE) String() string {
	return proto.EnumName(Resource_TYPE_name, int32(x))
}

func (Resource_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{1, 0}
}

type SingleResourceRequest_Action int32

const (
	SingleResourceRequest_LOOKUP  SingleResourceRequest_Action = 0
	SingleResourceRequest_REPLACE SingleResourceRequest_Action = 1
	SingleResourceRequest_ADD     SingleResourceRequest_Action = 2
	SingleResourceRequest_REMOVE  SingleResourceRequest_Action = 3
	SingleResourceRequest_PUSH    SingleResourceRequest_Action = 4
	SingleResourceRequest_POP     SingleResourceRequest_Action = 5
)

var SingleResourceRequest_Action_name = map[int32]string{
	0: "LOOKUP",
	1: "REPLACE",
	2: "ADD",
	3: "REMOVE",
	4: "PUSH",
	5: "POP",
}

var SingleResourceRequest_Action_value = map[string]int32{
	"LOOKUP":  0,
	"REPLACE": 1,
	"ADD":     2,
	"REMOVE":  3,
	"PUSH":    4,
	"POP":     5,
}

func (x SingleResourceRequest_Action) String() string {
	return proto.EnumName(SingleResourceRequest_Action_name, int32(x))
}

func (SingleResourceRequest_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{2, 0}
}

type ResourceReply_Status int32

const (
	ResourceReply_OK           ResourceReply_Status = 0
	ResourceReply_NON_EXISTENT ResourceReply_Status = 1
	ResourceReply_BAD_LOT_ID   ResourceReply_Status = 2
	ResourceReply_MISMATCH     ResourceReply_Status = 3
	ResourceReply_BAD_QUANTITY ResourceReply_Status = 4
	ResourceReply_MISSING      ResourceReply_Status = 5
	ResourceReply_INTERNAL     ResourceReply_Status = 6
)

var ResourceReply_Status_name = map[int32]string{
	0: "OK",
	1: "NON_EXISTENT",
	2: "BAD_LOT_ID",
	3: "MISMATCH",
	4: "BAD_QUANTITY",
	5: "MISSING",
	6: "INTERNAL",
}

var ResourceReply_Status_value = map[string]int32{
	"OK":           0,
	"NON_EXISTENT": 1,
	"BAD_LOT_ID":   2,
	"MISMATCH":     3,
	"BAD_QUANTITY": 4,
	"MISSING":      5,
	"INTERNAL":     6,
}

func (x ResourceReply_Status) String() string {
	return proto.EnumName(ResourceReply_Status_name, int32(x))
}

func (ResourceReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{3, 0}
}

type ResourceReply_BadLotIDReasons int32

const (
	ResourceReply_UNSPECIFIED_BAD_LOT_ID_REASON ResourceReply_BadLotIDReasons = 0
	ResourceReply_UNAVAILABLE                   ResourceReply_BadLotIDReasons = 1
	ResourceReply_EXPIRED                       ResourceReply_BadLotIDReasons = 2
	ResourceReply_ON_HOLD                       ResourceReply_BadLotIDReasons = 3
	ResourceReply_IN_INSPECTION                 ResourceReply_BadLotIDReasons = 4
	ResourceReply_ALREADY_MOUNTED               ResourceReply_BadLotIDReasons = 5
	ResourceReply_MISS_PRECONDITION             ResourceReply_BadLotIDReasons = 6
)

var ResourceReply_BadLotIDReasons_name = map[int32]string{
	0: "UNSPECIFIED_BAD_LOT_ID_REASON",
	1: "UNAVAILABLE",
	2: "EXPIRED",
	3: "ON_HOLD",
	4: "IN_INSPECTION",
	5: "ALREADY_MOUNTED",
	6: "MISS_PRECONDITION",
}

var ResourceReply_BadLotIDReasons_value = map[string]int32{
	"UNSPECIFIED_BAD_LOT_ID_REASON": 0,
	"UNAVAILABLE":                   1,
	"EXPIRED":                       2,
	"ON_HOLD":                       3,
	"IN_INSPECTION":                 4,
	"ALREADY_MOUNTED":               5,
	"MISS_PRECONDITION":             6,
}

func (x ResourceReply_BadLotIDReasons) String() string {
	return proto.EnumName(ResourceReply_BadLotIDReasons_name, int32(x))
}

func (ResourceReply_BadLotIDReasons) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{3, 1}
}

type ResourceReply_BadQuantityReasons int32

const (
	ResourceReply_UNSPECIFIED_BAD_QUANTITY_REASON ResourceReply_BadQuantityReasons = 0
	ResourceReply_SHORTAGE                        ResourceReply_BadQuantityReasons = 1
	ResourceReply_BELOW_MIS_USAGE                 ResourceReply_BadQuantityReasons = 2
)

var ResourceReply_BadQuantityReasons_name = map[int32]string{
	0: "UNSPECIFIED_BAD_QUANTITY_REASON",
	1: "SHORTAGE",
	2: "BELOW_MIS_USAGE",
}

var ResourceReply_BadQuantityReasons_value = map[string]int32{
	"UNSPECIFIED_BAD_QUANTITY_REASON": 0,
	"SHORTAGE":                        1,
	"BELOW_MIS_USAGE":                 2,
}

func (x ResourceReply_BadQuantityReasons) String() string {
	return proto.EnumName(ResourceReply_BadQuantityReasons_name, int32(x))
}

func (ResourceReply_BadQuantityReasons) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{3, 2}
}

type ResourceReply_InternalReasons int32

const (
	ResourceReply_UNSPECIFIED_INTERNAL_REASON ResourceReply_InternalReasons = 0
	ResourceReply_WRONG_SHEET_STATUS          ResourceReply_InternalReasons = 1
	ResourceReply_WRONG_WORK_ORDER_STATUS     ResourceReply_InternalReasons = 2
)

var ResourceReply_InternalReasons_name = map[int32]string{
	0: "UNSPECIFIED_INTERNAL_REASON",
	1: "WRONG_SHEET_STATUS",
	2: "WRONG_WORK_ORDER_STATUS",
}

var ResourceReply_InternalReasons_value = map[string]int32{
	"UNSPECIFIED_INTERNAL_REASON": 0,
	"WRONG_SHEET_STATUS":          1,
	"WRONG_WORK_ORDER_STATUS":     2,
}

func (x ResourceReply_InternalReasons) String() string {
	return proto.EnumName(ResourceReply_InternalReasons_name, int32(x))
}

func (ResourceReply_InternalReasons) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{3, 3}
}

type StartRequest_ContainerUseMode int32

const (
	StartRequest_UNSPECIFIED_MODE StartRequest_ContainerUseMode = 0
	// 統槽全用
	StartRequest_ALL StartRequest_ContainerUseMode = 1
	// 不指定統槽 , 自動從RECIPE相應桶槽抓資料, 確認標準量
	StartRequest_SUBSET StartRequest_ContainerUseMode = 2
	// 指定統槽
	StartRequest_ASSIGNED StartRequest_ContainerUseMode = 3
)

var StartRequest_ContainerUseMode_name = map[int32]string{
	0: "UNSPECIFIED_MODE",
	1: "ALL",
	2: "SUBSET",
	3: "ASSIGNED",
}

var StartRequest_ContainerUseMode_value = map[string]int32{
	"UNSPECIFIED_MODE": 0,
	"ALL":              1,
	"SUBSET":           2,
	"ASSIGNED":         3,
}

func (x StartRequest_ContainerUseMode) String() string {
	return proto.EnumName(StartRequest_ContainerUseMode_name, int32(x))
}

func (StartRequest_ContainerUseMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{4, 0}
}

type StartReply_Status int32

const (
	StartReply_OK       StartReply_Status = 0
	StartReply_INTERNAL StartReply_Status = 1
)

var StartReply_Status_name = map[int32]string{
	0: "OK",
	1: "INTERNAL",
}

var StartReply_Status_value = map[string]int32{
	"OK":       0,
	"INTERNAL": 1,
}

func (x StartReply_Status) String() string {
	return proto.EnumName(StartReply_Status_name, int32(x))
}

func (StartReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{5, 0}
}

type StartReply_InternalReasons int32

const (
	StartReply_UNSPECIFIED_INTERNAL_REASON StartReply_InternalReasons = 0
	StartReply_WRONG_BATCH_STATUS          StartReply_InternalReasons = 1
	StartReply_WRONG_WORK_ORDER_STATUS     StartReply_InternalReasons = 2
)

var StartReply_InternalReasons_name = map[int32]string{
	0: "UNSPECIFIED_INTERNAL_REASON",
	1: "WRONG_BATCH_STATUS",
	2: "WRONG_WORK_ORDER_STATUS",
}

var StartReply_InternalReasons_value = map[string]int32{
	"UNSPECIFIED_INTERNAL_REASON": 0,
	"WRONG_BATCH_STATUS":          1,
	"WRONG_WORK_ORDER_STATUS":     2,
}

func (x StartReply_InternalReasons) String() string {
	return proto.EnumName(StartReply_InternalReasons_name, int32(x))
}

func (StartReply_InternalReasons) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{5, 1}
}

// reply status code
type OutReply_Status int32

const (
	// 成功
	OutReply_OK         OutReply_Status = 0
	OutReply_INTERNAL   OutReply_Status = 1
	OutReply_BAD_LOT_ID OutReply_Status = 2
)

var OutReply_Status_name = map[int32]string{
	0: "OK",
	1: "INTERNAL",
	2: "BAD_LOT_ID",
}

var OutReply_Status_value = map[string]int32{
	"OK":         0,
	"INTERNAL":   1,
	"BAD_LOT_ID": 2,
}

func (x OutReply_Status) String() string {
	return proto.EnumName(OutReply_Status_name, int32(x))
}

func (OutReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{7, 0}
}

type OutReply_InternalReasons int32

const (
	OutReply_UNSPECIFIED_INTERNAL_REASON OutReply_InternalReasons = 0
	OutReply_WRONG_BATCH_STATUS          OutReply_InternalReasons = 1
	OutReply_WRONG_WORK_ORDER_STATUS     OutReply_InternalReasons = 2
	OutReply_NOT_FOUND_RECIPE_PROCESS    OutReply_InternalReasons = 3
)

var OutReply_InternalReasons_name = map[int32]string{
	0: "UNSPECIFIED_INTERNAL_REASON",
	1: "WRONG_BATCH_STATUS",
	2: "WRONG_WORK_ORDER_STATUS",
	3: "NOT_FOUND_RECIPE_PROCESS",
}

var OutReply_InternalReasons_value = map[string]int32{
	"UNSPECIFIED_INTERNAL_REASON": 0,
	"WRONG_BATCH_STATUS":          1,
	"WRONG_WORK_ORDER_STATUS":     2,
	"NOT_FOUND_RECIPE_PROCESS":    3,
}

func (x OutReply_InternalReasons) String() string {
	return proto.EnumName(OutReply_InternalReasons_name, int32(x))
}

func (OutReply_InternalReasons) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{7, 1}
}

type OutReply_BadLotIdReasons int32

const (
	OutReply_UNSPECIFIED_BAD_LOT_ID_REASON OutReply_BadLotIdReasons = 0
	OutReply_MATERIAL_NON_EXISTENT         OutReply_BadLotIdReasons = 1
	OutReply_MATERIAL_DUPLICATE            OutReply_BadLotIdReasons = 2
	OutReply_CARRIER_NON_EXISTENT          OutReply_BadLotIdReasons = 3
)

var OutReply_BadLotIdReasons_name = map[int32]string{
	0: "UNSPECIFIED_BAD_LOT_ID_REASON",
	1: "MATERIAL_NON_EXISTENT",
	2: "MATERIAL_DUPLICATE",
	3: "CARRIER_NON_EXISTENT",
}

var OutReply_BadLotIdReasons_value = map[string]int32{
	"UNSPECIFIED_BAD_LOT_ID_REASON": 0,
	"MATERIAL_NON_EXISTENT":         1,
	"MATERIAL_DUPLICATE":            2,
	"CARRIER_NON_EXISTENT":          3,
}

func (x OutReply_BadLotIdReasons) String() string {
	return proto.EnumName(OutReply_BadLotIdReasons_name, int32(x))
}

func (OutReply_BadLotIdReasons) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{7, 2}
}

// reply status code
type CloseReply_Status int32

const (
	CloseReply_OK                      CloseReply_Status = 0
	CloseReply_WRONG_WORK_ORDER_STATUS CloseReply_Status = 1
	CloseReply_WAIT_FOR_INPUT          CloseReply_Status = 2
	CloseReply_WAIT_FOR_OUTPUT         CloseReply_Status = 3
)

var CloseReply_Status_name = map[int32]string{
	0: "OK",
	1: "WRONG_WORK_ORDER_STATUS",
	2: "WAIT_FOR_INPUT",
	3: "WAIT_FOR_OUTPUT",
}

var CloseReply_Status_value = map[string]int32{
	"OK":                      0,
	"WRONG_WORK_ORDER_STATUS": 1,
	"WAIT_FOR_INPUT":          2,
	"WAIT_FOR_OUTPUT":         3,
}

func (x CloseReply_Status) String() string {
	return proto.EnumName(CloseReply_Status_name, int32(x))
}

func (CloseReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{9, 0}
}

type SignRequest_Mode int32

const (
	SignRequest_NONE SignRequest_Mode = 0
	SignRequest_IN   SignRequest_Mode = 1
	SignRequest_OUT  SignRequest_Mode = 2
)

var SignRequest_Mode_name = map[int32]string{
	0: "NONE",
	1: "IN",
	2: "OUT",
}

var SignRequest_Mode_value = map[string]int32{
	"NONE": 0,
	"IN":   1,
	"OUT":  2,
}

func (x SignRequest_Mode) String() string {
	return proto.EnumName(SignRequest_Mode_name, int32(x))
}

func (SignRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{10, 0}
}

type SignReply_Status int32

const (
	SignReply_OK                SignReply_Status = 0
	SignReply_PERMISSION_DENIED SignReply_Status = 1
)

var SignReply_Status_name = map[int32]string{
	0: "OK",
	1: "PERMISSION_DENIED",
}

var SignReply_Status_value = map[string]int32{
	"OK":                0,
	"PERMISSION_DENIED": 1,
}

func (x SignReply_Status) String() string {
	return proto.EnumName(SignReply_Status_name, int32(x))
}

func (SignReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{11, 0}
}

// 機台基本資訊透過 incoming context取得 , 此定義不會使用在 Request/Reply
type Context struct {
	Station              string   `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	WorkOrder            string   `protobuf:"bytes,2,opt,name=work_order,json=workOrder,proto3" json:"work_order,omitempty"`
	Batch                string   `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	Worker               string   `protobuf:"bytes,4,opt,name=worker,proto3" json:"worker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetStation() string {
	if m != nil {
		return m.Station
	}
	return ""
}

func (m *Context) GetWorkOrder() string {
	if m != nil {
		return m.WorkOrder
	}
	return ""
}

func (m *Context) GetBatch() string {
	if m != nil {
		return m.Batch
	}
	return ""
}

func (m *Context) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

//
//definition of action:
//1. LOOKUP : 取Resource資訊
//1.2 當Context包含工單號碼&機台時，檢查該Resource是否符合工單需求，回傳的數量則為配合表用量，非庫存量
//1.3 當auto_push = true 時主動將材料掛載至桶槽。Slot有資料則依Slot掛載，沒有則依配合維護桶位掛載
//
//3. ADD : 紀錄作業員, 工單, 首, 材料用量
//3.1 從Context取得機台, 作業員工號, 工單ID, 首編號
//3.2 將材料寫入DB進行暫存 (Wait For Start)
//3.3 commit == True 時檢查 中央供應材料數量是否足夠 , 治工具是否到齊
//
//4. REMOVE  : 刪除指定Slot上的Resource
//2. REPLACE : 將指定Slot上的Resource 替換成 request Resource
//5. PUSH    : 往指定Slot推送Resource
//6. POP     : 拿掉指定Slot的front Resource (FIFO)
//
//注： 以上所有ACTION預設回傳Resource訊息
type Resource struct {
	Type                 Resource_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=proto.mes.Resource_TYPE" json:"type,omitempty"`
	LotId                string        `protobuf:"bytes,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{1}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() Resource_TYPE {
	if m != nil {
		return m.Type
	}
	return Resource_UNSPECIFIED
}

func (m *Resource) GetLotId() string {
	if m != nil {
		return m.LotId
	}
	return ""
}

type SingleResourceRequest struct {
	Action   SingleResourceRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=proto.mes.SingleResourceRequest_Action" json:"action,omitempty"`
	Resource *Resource                    `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Slot     *SingleResourceRequest_Slot  `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	Quantity float32                      `protobuf:"fixed32,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// @cliff when action = LOOKUP: 從context取工單後，確認該材料符合工單就自動掛載
	AutoPush             bool     `protobuf:"varint,5,opt,name=auto_push,json=autoPush,proto3" json:"auto_push,omitempty"`
	AutoStart            bool     `protobuf:"varint,6,opt,name=auto_start,json=autoStart,proto3" json:"auto_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleResourceRequest) Reset()         { *m = SingleResourceRequest{} }
func (m *SingleResourceRequest) String() string { return proto.CompactTextString(m) }
func (*SingleResourceRequest) ProtoMessage()    {}
func (*SingleResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{2}
}

func (m *SingleResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleResourceRequest.Unmarshal(m, b)
}
func (m *SingleResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleResourceRequest.Marshal(b, m, deterministic)
}
func (m *SingleResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleResourceRequest.Merge(m, src)
}
func (m *SingleResourceRequest) XXX_Size() int {
	return xxx_messageInfo_SingleResourceRequest.Size(m)
}
func (m *SingleResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SingleResourceRequest proto.InternalMessageInfo

func (m *SingleResourceRequest) GetAction() SingleResourceRequest_Action {
	if m != nil {
		return m.Action
	}
	return SingleResourceRequest_LOOKUP
}

func (m *SingleResourceRequest) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *SingleResourceRequest) GetSlot() *SingleResourceRequest_Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func (m *SingleResourceRequest) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SingleResourceRequest) GetAutoPush() bool {
	if m != nil {
		return m.AutoPush
	}
	return false
}

func (m *SingleResourceRequest) GetAutoStart() bool {
	if m != nil {
		return m.AutoStart
	}
	return false
}

type SingleResourceRequest_Slot struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleResourceRequest_Slot) Reset()         { *m = SingleResourceRequest_Slot{} }
func (m *SingleResourceRequest_Slot) String() string { return proto.CompactTextString(m) }
func (*SingleResourceRequest_Slot) ProtoMessage()    {}
func (*SingleResourceRequest_Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{2, 0}
}

func (m *SingleResourceRequest_Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleResourceRequest_Slot.Unmarshal(m, b)
}
func (m *SingleResourceRequest_Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleResourceRequest_Slot.Marshal(b, m, deterministic)
}
func (m *SingleResourceRequest_Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleResourceRequest_Slot.Merge(m, src)
}
func (m *SingleResourceRequest_Slot) XXX_Size() int {
	return xxx_messageInfo_SingleResourceRequest_Slot.Size(m)
}
func (m *SingleResourceRequest_Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleResourceRequest_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_SingleResourceRequest_Slot proto.InternalMessageInfo

func (m *SingleResourceRequest_Slot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SingleResourceRequest_Slot) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ResourceReply struct {
	RequestedResource *Resource            `protobuf:"bytes,1,opt,name=requested_resource,json=requestedResource,proto3" json:"requested_resource,omitempty"`
	Status            ResourceReply_Status `protobuf:"varint,2,opt,name=status,proto3,enum=proto.mes.ResourceReply_Status" json:"status,omitempty"`
	Quantity          float32              `protobuf:"fixed32,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Id                string               `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Level             string               `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Date              string               `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	ExpiryDate        string               `protobuf:"bytes,7,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	// @cliff 查詢的結果需要多一個配方標準用量顯示在HMI上
	StandardDosage      float32 `protobuf:"fixed32,8,opt,name=standard_dosage,json=standardDosage,proto3" json:"standard_dosage,omitempty"`
	StandardErrorMargin float32 `protobuf:"fixed32,9,opt,name=standard_error_margin,json=standardErrorMargin,proto3" json:"standard_error_margin,omitempty"`
	// Types that are valid to be assigned to Reason:
	//	*ResourceReply_BadLotIDReasons_
	//	*ResourceReply_BadQuantityReasons_
	//	*ResourceReply_InternalReasons_
	Reason               isResourceReply_Reason `protobuf_oneof:"reason"`
	Aux                  string                 `protobuf:"bytes,100,opt,name=aux,proto3" json:"aux,omitempty"`
	Properties           map[string]string      `protobuf:"bytes,102,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResourceReply) Reset()         { *m = ResourceReply{} }
func (m *ResourceReply) String() string { return proto.CompactTextString(m) }
func (*ResourceReply) ProtoMessage()    {}
func (*ResourceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{3}
}

func (m *ResourceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceReply.Unmarshal(m, b)
}
func (m *ResourceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceReply.Marshal(b, m, deterministic)
}
func (m *ResourceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceReply.Merge(m, src)
}
func (m *ResourceReply) XXX_Size() int {
	return xxx_messageInfo_ResourceReply.Size(m)
}
func (m *ResourceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceReply.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceReply proto.InternalMessageInfo

func (m *ResourceReply) GetRequestedResource() *Resource {
	if m != nil {
		return m.RequestedResource
	}
	return nil
}

func (m *ResourceReply) GetStatus() ResourceReply_Status {
	if m != nil {
		return m.Status
	}
	return ResourceReply_OK
}

func (m *ResourceReply) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *ResourceReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResourceReply) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *ResourceReply) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ResourceReply) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *ResourceReply) GetStandardDosage() float32 {
	if m != nil {
		return m.StandardDosage
	}
	return 0
}

func (m *ResourceReply) GetStandardErrorMargin() float32 {
	if m != nil {
		return m.StandardErrorMargin
	}
	return 0
}

type isResourceReply_Reason interface {
	isResourceReply_Reason()
}

type ResourceReply_BadLotIDReasons_ struct {
	BadLotIDReasons ResourceReply_BadLotIDReasons `protobuf:"varint,10,opt,name=badLotIDReasons,proto3,enum=proto.mes.ResourceReply_BadLotIDReasons,oneof"`
}

type ResourceReply_BadQuantityReasons_ struct {
	BadQuantityReasons ResourceReply_BadQuantityReasons `protobuf:"varint,11,opt,name=badQuantityReasons,proto3,enum=proto.mes.ResourceReply_BadQuantityReasons,oneof"`
}

type ResourceReply_InternalReasons_ struct {
	InternalReasons ResourceReply_InternalReasons `protobuf:"varint,12,opt,name=internalReasons,proto3,enum=proto.mes.ResourceReply_InternalReasons,oneof"`
}

func (*ResourceReply_BadLotIDReasons_) isResourceReply_Reason() {}

func (*ResourceReply_BadQuantityReasons_) isResourceReply_Reason() {}

func (*ResourceReply_InternalReasons_) isResourceReply_Reason() {}

func (m *ResourceReply) GetReason() isResourceReply_Reason {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *ResourceReply) GetBadLotIDReasons() ResourceReply_BadLotIDReasons {
	if x, ok := m.GetReason().(*ResourceReply_BadLotIDReasons_); ok {
		return x.BadLotIDReasons
	}
	return ResourceReply_UNSPECIFIED_BAD_LOT_ID_REASON
}

func (m *ResourceReply) GetBadQuantityReasons() ResourceReply_BadQuantityReasons {
	if x, ok := m.GetReason().(*ResourceReply_BadQuantityReasons_); ok {
		return x.BadQuantityReasons
	}
	return ResourceReply_UNSPECIFIED_BAD_QUANTITY_REASON
}

func (m *ResourceReply) GetInternalReasons() ResourceReply_InternalReasons {
	if x, ok := m.GetReason().(*ResourceReply_InternalReasons_); ok {
		return x.InternalReasons
	}
	return ResourceReply_UNSPECIFIED_INTERNAL_REASON
}

func (m *ResourceReply) GetAux() string {
	if m != nil {
		return m.Aux
	}
	return ""
}

func (m *ResourceReply) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ResourceReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ResourceReply_BadLotIDReasons_)(nil),
		(*ResourceReply_BadQuantityReasons_)(nil),
		(*ResourceReply_InternalReasons_)(nil),
	}
}

//
//對應白板的 Start :
//1. 透過Context取得機台, 作業員工號, 工單ID, 首編號
//2. Start代表該首已不會再投料, 承認先前ADD的所有紀錄 (COPY到SHEET BOM)
//3. 檢查未ADD到齊的材料 (與RECIPE相比, 包含流水線上及桶槽) , 使用量以標準用量紀錄, 補齊沒ADD的資訊
type StartRequest struct {
	ContainerUseMode StartRequest_ContainerUseMode `protobuf:"varint,1,opt,name=container_use_mode,json=containerUseMode,proto3,enum=proto.mes.StartRequest_ContainerUseMode" json:"container_use_mode,omitempty"`
	// MODE為ASSIGNED時, 需要給資料
	ContainerId          []string `protobuf:"bytes,2,rep,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{4}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetContainerUseMode() StartRequest_ContainerUseMode {
	if m != nil {
		return m.ContainerUseMode
	}
	return StartRequest_UNSPECIFIED_MODE
}

func (m *StartRequest) GetContainerId() []string {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type StartReply struct {
	// reply status code
	Status               StartReply_Status          `protobuf:"varint,1,opt,name=status,proto3,enum=proto.mes.StartReply_Status" json:"status,omitempty"`
	InternalReasons      StartReply_InternalReasons `protobuf:"varint,2,opt,name=internalReasons,proto3,enum=proto.mes.StartReply_InternalReasons" json:"internalReasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StartReply) Reset()         { *m = StartReply{} }
func (m *StartReply) String() string { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()    {}
func (*StartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{5}
}

func (m *StartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReply.Unmarshal(m, b)
}
func (m *StartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReply.Marshal(b, m, deterministic)
}
func (m *StartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReply.Merge(m, src)
}
func (m *StartReply) XXX_Size() int {
	return xxx_messageInfo_StartReply.Size(m)
}
func (m *StartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartReply proto.InternalMessageInfo

func (m *StartReply) GetStatus() StartReply_Status {
	if m != nil {
		return m.Status
	}
	return StartReply_OK
}

func (m *StartReply) GetInternalReasons() StartReply_InternalReasons {
	if m != nil {
		return m.InternalReasons
	}
	return StartReply_UNSPECIFIED_INTERNAL_REASON
}

//
//白板沒有:  收料, 紀錄收料資訊
//1. 透過Context取得機台, 作業員工號, 工單ID
//2. 驗證材料標示卡是否正確, 載具是否存在
//3. 檢查是否可收: 投入首數 - 產出首數
//4. 更新工單, 首資訊, 更新庫存
type OutRequest struct {
	// 收料量
	Qty float32 `protobuf:"fixed32,1,opt,name=qty,proto3" json:"qty,omitempty"`
	// 標示卡條碼 (自動列印時不用)
	MaterialLotId string `protobuf:"bytes,2,opt,name=material_lot_id,json=materialLotId,proto3" json:"material_lot_id,omitempty"`
	// 載具條碼
	CarrierId            string   `protobuf:"bytes,3,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutRequest) Reset()         { *m = OutRequest{} }
func (m *OutRequest) String() string { return proto.CompactTextString(m) }
func (*OutRequest) ProtoMessage()    {}
func (*OutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{6}
}

func (m *OutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutRequest.Unmarshal(m, b)
}
func (m *OutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutRequest.Marshal(b, m, deterministic)
}
func (m *OutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutRequest.Merge(m, src)
}
func (m *OutRequest) XXX_Size() int {
	return xxx_messageInfo_OutRequest.Size(m)
}
func (m *OutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutRequest proto.InternalMessageInfo

func (m *OutRequest) GetQty() float32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *OutRequest) GetMaterialLotId() string {
	if m != nil {
		return m.MaterialLotId
	}
	return ""
}

func (m *OutRequest) GetCarrierId() string {
	if m != nil {
		return m.CarrierId
	}
	return ""
}

type OutReply struct {
	// reply status code
	Status OutReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.mes.OutReply_Status" json:"status,omitempty"`
	// Types that are valid to be assigned to Reason:
	//	*OutReply_BadLotIdReasons_
	//	*OutReply_InternalReasons_
	Reason               isOutReply_Reason `protobuf_oneof:"reason"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OutReply) Reset()         { *m = OutReply{} }
func (m *OutReply) String() string { return proto.CompactTextString(m) }
func (*OutReply) ProtoMessage()    {}
func (*OutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{7}
}

func (m *OutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutReply.Unmarshal(m, b)
}
func (m *OutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutReply.Marshal(b, m, deterministic)
}
func (m *OutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutReply.Merge(m, src)
}
func (m *OutReply) XXX_Size() int {
	return xxx_messageInfo_OutReply.Size(m)
}
func (m *OutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OutReply.DiscardUnknown(m)
}

var xxx_messageInfo_OutReply proto.InternalMessageInfo

func (m *OutReply) GetStatus() OutReply_Status {
	if m != nil {
		return m.Status
	}
	return OutReply_OK
}

type isOutReply_Reason interface {
	isOutReply_Reason()
}

type OutReply_BadLotIdReasons_ struct {
	BadLotIdReasons OutReply_BadLotIdReasons `protobuf:"varint,11,opt,name=badLotIdReasons,proto3,enum=proto.mes.OutReply_BadLotIdReasons,oneof"`
}

type OutReply_InternalReasons_ struct {
	InternalReasons OutReply_InternalReasons `protobuf:"varint,12,opt,name=internalReasons,proto3,enum=proto.mes.OutReply_InternalReasons,oneof"`
}

func (*OutReply_BadLotIdReasons_) isOutReply_Reason() {}

func (*OutReply_InternalReasons_) isOutReply_Reason() {}

func (m *OutReply) GetReason() isOutReply_Reason {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *OutReply) GetBadLotIdReasons() OutReply_BadLotIdReasons {
	if x, ok := m.GetReason().(*OutReply_BadLotIdReasons_); ok {
		return x.BadLotIdReasons
	}
	return OutReply_UNSPECIFIED_BAD_LOT_ID_REASON
}

func (m *OutReply) GetInternalReasons() OutReply_InternalReasons {
	if x, ok := m.GetReason().(*OutReply_InternalReasons_); ok {
		return x.InternalReasons
	}
	return OutReply_UNSPECIFIED_INTERNAL_REASON
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OutReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OutReply_BadLotIdReasons_)(nil),
		(*OutReply_InternalReasons_)(nil),
	}
}

//
//對應白板的 Close : 投料或收料結束, 變更工單狀態為下一狀態
//1. 透過Context取得機台, 作業員工號, 工單ID, 並進行工單狀態切換
//2. 當工單狀態為已開始投料(input) -> 更新為投料完畢(processing) ,
//當工單狀態為投料完畢(processing) -> 更新為收料完畢(completed)
type CloseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{8}
}

func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (m *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(m, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

type CloseReply struct {
	// reply status code
	Status               CloseReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.mes.CloseReply_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CloseReply) Reset()         { *m = CloseReply{} }
func (m *CloseReply) String() string { return proto.CompactTextString(m) }
func (*CloseReply) ProtoMessage()    {}
func (*CloseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{9}
}

func (m *CloseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseReply.Unmarshal(m, b)
}
func (m *CloseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseReply.Marshal(b, m, deterministic)
}
func (m *CloseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseReply.Merge(m, src)
}
func (m *CloseReply) XXX_Size() int {
	return xxx_messageInfo_CloseReply.Size(m)
}
func (m *CloseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CloseReply proto.InternalMessageInfo

func (m *CloseReply) GetStatus() CloseReply_Status {
	if m != nil {
		return m.Status
	}
	return CloseReply_OK
}

//
//白板沒有:  登入/登出 驗證
//1. 從Context 取得機台, 作業員工號
//2. 透過員工主檔驗證員工是否存在 (機台可以取得管理廠, 再取得子公司)
type SignRequest struct {
	// 登入/登出
	Mode                 SignRequest_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=proto.mes.SignRequest_Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{10}
}

func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (m *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(m, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetMode() SignRequest_Mode {
	if m != nil {
		return m.Mode
	}
	return SignRequest_NONE
}

type SignReply struct {
	Status               SignReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.mes.SignReply_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignReply) Reset()         { *m = SignReply{} }
func (m *SignReply) String() string { return proto.CompactTextString(m) }
func (*SignReply) ProtoMessage()    {}
func (*SignReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d821c6c65805fb4, []int{11}
}

func (m *SignReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignReply.Unmarshal(m, b)
}
func (m *SignReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignReply.Marshal(b, m, deterministic)
}
func (m *SignReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignReply.Merge(m, src)
}
func (m *SignReply) XXX_Size() int {
	return xxx_messageInfo_SignReply.Size(m)
}
func (m *SignReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignReply proto.InternalMessageInfo

func (m *SignReply) GetStatus() SignReply_Status {
	if m != nil {
		return m.Status
	}
	return SignReply_OK
}

func init() {
	proto.RegisterEnum("proto.mes.Resource_TYPE", Resource_TYPE_name, Resource_TYPE_value)
	proto.RegisterEnum("proto.mes.SingleResourceRequest_Action", SingleResourceRequest_Action_name, SingleResourceRequest_Action_value)
	proto.RegisterEnum("proto.mes.ResourceReply_Status", ResourceReply_Status_name, ResourceReply_Status_value)
	proto.RegisterEnum("proto.mes.ResourceReply_BadLotIDReasons", ResourceReply_BadLotIDReasons_name, ResourceReply_BadLotIDReasons_value)
	proto.RegisterEnum("proto.mes.ResourceReply_BadQuantityReasons", ResourceReply_BadQuantityReasons_name, ResourceReply_BadQuantityReasons_value)
	proto.RegisterEnum("proto.mes.ResourceReply_InternalReasons", ResourceReply_InternalReasons_name, ResourceReply_InternalReasons_value)
	proto.RegisterEnum("proto.mes.StartRequest_ContainerUseMode", StartRequest_ContainerUseMode_name, StartRequest_ContainerUseMode_value)
	proto.RegisterEnum("proto.mes.StartReply_Status", StartReply_Status_name, StartReply_Status_value)
	proto.RegisterEnum("proto.mes.StartReply_InternalReasons", StartReply_InternalReasons_name, StartReply_InternalReasons_value)
	proto.RegisterEnum("proto.mes.OutReply_Status", OutReply_Status_name, OutReply_Status_value)
	proto.RegisterEnum("proto.mes.OutReply_InternalReasons", OutReply_InternalReasons_name, OutReply_InternalReasons_value)
	proto.RegisterEnum("proto.mes.OutReply_BadLotIdReasons", OutReply_BadLotIdReasons_name, OutReply_BadLotIdReasons_value)
	proto.RegisterEnum("proto.mes.CloseReply_Status", CloseReply_Status_name, CloseReply_Status_value)
	proto.RegisterEnum("proto.mes.SignRequest_Mode", SignRequest_Mode_name, SignRequest_Mode_value)
	proto.RegisterEnum("proto.mes.SignReply_Status", SignReply_Status_name, SignReply_Status_value)
	proto.RegisterType((*Context)(nil), "proto.mes.Context")
	proto.RegisterType((*Resource)(nil), "proto.mes.Resource")
	proto.RegisterType((*SingleResourceRequest)(nil), "proto.mes.SingleResourceRequest")
	proto.RegisterType((*SingleResourceRequest_Slot)(nil), "proto.mes.SingleResourceRequest.Slot")
	proto.RegisterType((*ResourceReply)(nil), "proto.mes.ResourceReply")
	proto.RegisterMapType((map[string]string)(nil), "proto.mes.ResourceReply.PropertiesEntry")
	proto.RegisterType((*StartRequest)(nil), "proto.mes.StartRequest")
	proto.RegisterType((*StartReply)(nil), "proto.mes.StartReply")
	proto.RegisterType((*OutRequest)(nil), "proto.mes.OutRequest")
	proto.RegisterType((*OutReply)(nil), "proto.mes.OutReply")
	proto.RegisterType((*CloseRequest)(nil), "proto.mes.CloseRequest")
	proto.RegisterType((*CloseReply)(nil), "proto.mes.CloseReply")
	proto.RegisterType((*SignRequest)(nil), "proto.mes.SignRequest")
	proto.RegisterType((*SignReply)(nil), "proto.mes.SignReply")
}

func init() { proto.RegisterFile("v2-1.proto", fileDescriptor_5d821c6c65805fb4) }

var fileDescriptor_5d821c6c65805fb4 = []byte{
	// 1472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0x34, 0x4d, 0x4e, 0xb2, 0x89, 0x3b, 0xdd, 0x2e, 0xa1, 0xdd, 0x5f, 0xaf, 0x96,
	0xad, 0x04, 0x64, 0x21, 0x8b, 0xc4, 0x8f, 0x84, 0x90, 0x13, 0xcf, 0x36, 0x56, 0x13, 0x8f, 0x77,
	0xec, 0xb4, 0xbb, 0x12, 0xc8, 0x72, 0xeb, 0xa1, 0x6b, 0x6d, 0x1a, 0x67, 0x6d, 0x67, 0x69, 0xef,
	0xe0, 0x82, 0x87, 0x00, 0x21, 0x2e, 0x79, 0x24, 0x1e, 0x81, 0xe7, 0x40, 0x33, 0x89, 0xdd, 0xc4,
	0xc9, 0xb6, 0x20, 0x24, 0xae, 0xe2, 0x39, 0xe7, 0x9b, 0x73, 0xce, 0x9c, 0x9f, 0x6f, 0x26, 0x00,
	0x6f, 0x5b, 0x1f, 0x7f, 0xda, 0x1c, 0x87, 0x41, 0x1c, 0xa0, 0xb2, 0xf8, 0x69, 0x9e, 0xb1, 0x48,
	0x19, 0xc3, 0x46, 0x27, 0x18, 0xc5, 0xec, 0x3c, 0x46, 0x0d, 0xd8, 0x88, 0x62, 0x37, 0xf6, 0x83,
	0x51, 0x43, 0xba, 0x2f, 0xed, 0x95, 0x69, 0xb2, 0x44, 0x77, 0x00, 0x7e, 0x08, 0xc2, 0xd7, 0x4e,
	0x10, 0x7a, 0x2c, 0x6c, 0xe4, 0x84, 0xb2, 0xcc, 0x25, 0x84, 0x0b, 0xd0, 0x4d, 0x58, 0x3f, 0x76,
	0xe3, 0x93, 0x57, 0x8d, 0xbc, 0xd0, 0x4c, 0x17, 0xe8, 0x16, 0x14, 0x39, 0x84, 0x85, 0x8d, 0x82,
	0x10, 0xcf, 0x56, 0xca, 0x8f, 0x12, 0x94, 0x28, 0x8b, 0x82, 0x49, 0x78, 0xc2, 0xd0, 0x47, 0x50,
	0x88, 0x2f, 0xc6, 0x4c, 0x38, 0xac, 0xb5, 0x1a, 0xcd, 0x34, 0xb0, 0x66, 0x02, 0x69, 0xda, 0x2f,
	0x4d, 0x4c, 0x05, 0x0a, 0x6d, 0x43, 0x71, 0x18, 0xc4, 0x8e, 0xef, 0xcd, 0x62, 0x58, 0x1f, 0x06,
	0xb1, 0xee, 0x29, 0x4f, 0xa0, 0xc0, 0x41, 0xa8, 0x0e, 0x95, 0x81, 0x61, 0x99, 0xb8, 0xa3, 0x3f,
	0xd3, 0xb1, 0x26, 0xaf, 0xa1, 0x12, 0x14, 0x6c, 0x42, 0x7a, 0xb2, 0x84, 0xaa, 0x50, 0xea, 0xab,
	0x36, 0xa6, 0xba, 0xda, 0x93, 0x73, 0xca, 0x2f, 0x79, 0xd8, 0xb6, 0xfc, 0xd1, 0xe9, 0x90, 0x25,
	0x5e, 0x28, 0x7b, 0x33, 0x61, 0x51, 0x8c, 0xbe, 0x81, 0xa2, 0x7b, 0x92, 0xa6, 0xa0, 0xd6, 0x7a,
	0x3c, 0x17, 0xd1, 0xca, 0x1d, 0x4d, 0x55, 0xc0, 0xe9, 0x6c, 0x1b, 0x7a, 0x02, 0xa5, 0x70, 0x86,
	0x10, 0x41, 0x56, 0x5a, 0x5b, 0x2b, 0x0e, 0x45, 0x53, 0x10, 0xfa, 0x12, 0x0a, 0xd1, 0x30, 0x88,
	0x45, 0xee, 0x2a, 0xad, 0x47, 0xd7, 0xfa, 0xb3, 0x86, 0x41, 0x4c, 0xc5, 0x16, 0xb4, 0x03, 0xa5,
	0x37, 0x13, 0x77, 0x14, 0xfb, 0xf1, 0x85, 0xc8, 0x71, 0x8e, 0xa6, 0x6b, 0xb4, 0x0b, 0x65, 0x77,
	0x12, 0x07, 0xce, 0x78, 0x12, 0xbd, 0x6a, 0xac, 0xdf, 0x97, 0xf6, 0x4a, 0xb4, 0xc4, 0x05, 0xe6,
	0x24, 0x7a, 0xc5, 0xeb, 0x29, 0x94, 0x51, 0xec, 0x86, 0x71, 0xa3, 0x28, 0xb4, 0x02, 0x6e, 0x71,
	0xc1, 0xce, 0x27, 0x50, 0xe0, 0x5e, 0x10, 0x82, 0xc2, 0xc8, 0x3d, 0x63, 0xb3, 0x6e, 0x10, 0xdf,
	0xbc, 0xd6, 0xfe, 0xc8, 0x63, 0xe7, 0xe2, 0x70, 0xeb, 0x74, 0xba, 0x50, 0x74, 0x28, 0x4e, 0xf3,
	0x80, 0x00, 0x8a, 0x3d, 0x42, 0x0e, 0x06, 0xa6, 0xbc, 0x86, 0x2a, 0xb0, 0x41, 0xb1, 0xd9, 0x53,
	0x3b, 0x58, 0x96, 0xd0, 0x06, 0xe4, 0x55, 0x4d, 0x93, 0x73, 0x1c, 0x41, 0x71, 0x9f, 0x1c, 0x62,
	0x39, 0xcf, 0x0b, 0x64, 0x0e, 0xac, 0xae, 0x5c, 0xe0, 0x6a, 0x93, 0x98, 0xf2, 0xba, 0xf2, 0x57,
	0x19, 0x6e, 0x5c, 0x9e, 0x79, 0x3c, 0xbc, 0x40, 0x6d, 0x40, 0xe1, 0xf4, 0xf0, 0xcc, 0x73, 0xd2,
	0xe4, 0x4a, 0xef, 0x4e, 0xee, 0x66, 0x0a, 0x4f, 0xfb, 0xec, 0x73, 0x28, 0xf2, 0x66, 0x9e, 0x44,
	0x22, 0xee, 0x5a, 0xeb, 0xde, 0xaa, 0x7d, 0xdc, 0x5b, 0xd3, 0x12, 0x30, 0x3a, 0x83, 0x2f, 0xe4,
	0x38, 0x9f, 0xc9, 0x71, 0x0d, 0x72, 0xbe, 0x37, 0xeb, 0xee, 0x9c, 0xef, 0xf1, 0xdc, 0x0c, 0xd9,
	0x5b, 0x36, 0x14, 0xf9, 0xe6, 0xdd, 0xc9, 0x17, 0x3c, 0x8b, 0x9e, 0x1b, 0x33, 0x91, 0xe6, 0x32,
	0x15, 0xdf, 0xe8, 0x2e, 0x00, 0x3b, 0x1f, 0xfb, 0xe1, 0x85, 0xc6, 0x35, 0x1b, 0x42, 0x33, 0x27,
	0x41, 0x8f, 0xa1, 0x1e, 0xc5, 0xee, 0xc8, 0x73, 0x43, 0xcf, 0xf1, 0x82, 0xc8, 0x3d, 0x65, 0x8d,
	0x92, 0x70, 0x5e, 0x4b, 0xc4, 0x9a, 0x90, 0xa2, 0x16, 0x6c, 0xa7, 0x40, 0x16, 0x86, 0x41, 0xe8,
	0x9c, 0xb9, 0xe1, 0xa9, 0x3f, 0x6a, 0x94, 0x05, 0x7c, 0x2b, 0x51, 0x62, 0xae, 0xeb, 0x0b, 0x15,
	0xb2, 0xa1, 0x7e, 0xec, 0x7a, 0xbd, 0x20, 0xd6, 0x35, 0xca, 0xdc, 0x28, 0x18, 0x45, 0x0d, 0x10,
	0x49, 0xd9, 0x7b, 0x67, 0x52, 0xda, 0x8b, 0xf8, 0xee, 0x1a, 0xcd, 0x9a, 0x40, 0xdf, 0x01, 0x3a,
	0x76, 0xbd, 0xe7, 0xb3, 0xdc, 0x24, 0x86, 0x2b, 0xc2, 0xf0, 0x87, 0x57, 0x19, 0xce, 0x6c, 0xe9,
	0xae, 0xd1, 0x15, 0x86, 0x78, 0xd0, 0xfe, 0x28, 0x66, 0xe1, 0xc8, 0x1d, 0x26, 0xb6, 0xab, 0xd7,
	0x04, 0xad, 0x2f, 0xe2, 0x79, 0xd0, 0x19, 0x13, 0x48, 0x86, 0xbc, 0x3b, 0x39, 0x6f, 0x78, 0xa2,
	0x00, 0xfc, 0x13, 0x75, 0x01, 0xc6, 0x61, 0x30, 0x66, 0x61, 0xec, 0xb3, 0xa8, 0xf1, 0xfd, 0xfd,
	0xfc, 0x5e, 0xe5, 0x0a, 0x17, 0x66, 0x0a, 0xc5, 0xa3, 0x38, 0xbc, 0xa0, 0x73, 0x7b, 0x77, 0xbe,
	0x86, 0x7a, 0x46, 0xcd, 0xdd, 0xbd, 0x66, 0x17, 0xb3, 0x79, 0xe2, 0x9f, 0xbc, 0x65, 0xde, 0xba,
	0xc3, 0x09, 0x4b, 0x08, 0x4d, 0x2c, 0xbe, 0xca, 0x7d, 0x21, 0x29, 0x67, 0x50, 0x9c, 0xb6, 0x22,
	0x2a, 0x42, 0x8e, 0x1c, 0xc8, 0x6b, 0x48, 0x86, 0xaa, 0x41, 0x0c, 0x07, 0xbf, 0xd0, 0x2d, 0x1b,
	0x1b, 0xb6, 0x2c, 0xa1, 0x1a, 0x40, 0x5b, 0xd5, 0x9c, 0x1e, 0xb1, 0x1d, 0x9d, 0x8f, 0x16, 0x67,
	0x39, 0xdd, 0xea, 0xab, 0x76, 0xa7, 0x2b, 0xe7, 0x39, 0x9e, 0x6b, 0x9f, 0x0f, 0x54, 0xc3, 0xd6,
	0xed, 0x97, 0x72, 0x81, 0x0f, 0x64, 0x5f, 0xb7, 0x2c, 0xdd, 0xd8, 0x97, 0xd7, 0x39, 0x58, 0x37,
	0x6c, 0x4c, 0x0d, 0xb5, 0x27, 0x17, 0x95, 0xdf, 0x25, 0xa8, 0x67, 0xaa, 0x8c, 0x1e, 0xc0, 0x9d,
	0x39, 0x3e, 0x75, 0x2e, 0x5d, 0x39, 0x14, 0xab, 0x16, 0x31, 0xe4, 0xb5, 0x29, 0xe5, 0xaa, 0x87,
	0xaa, 0xde, 0x53, 0xdb, 0x3d, 0x3e, 0xe6, 0x15, 0xd8, 0xc0, 0x2f, 0x4c, 0x9d, 0x62, 0x1e, 0x4f,
	0x05, 0x36, 0x88, 0xe1, 0x74, 0x49, 0x4f, 0x93, 0xf3, 0x68, 0x13, 0x6e, 0xe8, 0x86, 0xa3, 0x0b,
	0x83, 0xb6, 0x4e, 0x0c, 0xb9, 0x80, 0xb6, 0xa0, 0xae, 0xf6, 0x28, 0x56, 0xb5, 0x97, 0x4e, 0x9f,
	0x0c, 0x0c, 0x1b, 0x6b, 0xf2, 0x3a, 0xda, 0x86, 0x4d, 0x1e, 0xa4, 0x63, 0x52, 0xdc, 0x21, 0x86,
	0xa6, 0x0b, 0x6c, 0x51, 0xf9, 0x16, 0xd0, 0x72, 0xb3, 0xa0, 0x87, 0x70, 0x2f, 0x1b, 0x62, 0x72,
	0xde, 0xcb, 0x20, 0xab, 0x50, 0xb2, 0xba, 0x84, 0xda, 0xea, 0x3e, 0x8f, 0x70, 0x0b, 0xea, 0x6d,
	0xdc, 0x23, 0x47, 0x4e, 0x5f, 0xb7, 0x9c, 0x81, 0xc5, 0x85, 0x39, 0xe5, 0x14, 0xea, 0x99, 0x76,
	0x41, 0xf7, 0x60, 0x77, 0xde, 0x74, 0x92, 0xab, 0x4b, 0xb3, 0xb7, 0x00, 0x1d, 0x51, 0x62, 0xec,
	0x3b, 0x56, 0x17, 0x63, 0xdb, 0xb1, 0x6c, 0xd5, 0x1e, 0x58, 0xb2, 0x84, 0x76, 0xe1, 0xbd, 0xa9,
	0xfc, 0x88, 0xd0, 0x03, 0x87, 0x50, 0x0d, 0xd3, 0x44, 0x99, 0x6b, 0x97, 0xa0, 0x18, 0x0a, 0x07,
	0xca, 0x9f, 0x12, 0x54, 0x05, 0xdf, 0x26, 0x77, 0xcf, 0x21, 0xa0, 0x93, 0x60, 0x14, 0xbb, 0xfe,
	0x88, 0x85, 0xce, 0x24, 0x62, 0xce, 0x59, 0xe0, 0x25, 0x37, 0xe3, 0x7c, 0x0b, 0xce, 0x6f, 0x6a,
	0x76, 0x92, 0x1d, 0x83, 0x88, 0xf5, 0x03, 0x8f, 0x51, 0xf9, 0x24, 0x23, 0x41, 0x0f, 0xa0, 0x7a,
	0x69, 0x57, 0xdc, 0x9d, 0xf9, 0xbd, 0x32, 0xad, 0xa4, 0x32, 0xdd, 0x53, 0x0e, 0x40, 0xce, 0x1a,
	0x42, 0x37, 0x41, 0x9e, 0x3f, 0x7f, 0x9f, 0x68, 0x58, 0x5e, 0x13, 0x34, 0xde, 0xe3, 0x37, 0x2a,
	0x40, 0xd1, 0x1a, 0xb4, 0x2d, 0x6c, 0x4f, 0xfb, 0x4e, 0xb5, 0x2c, 0x7d, 0xdf, 0xc0, 0x9a, 0x9c,
	0x57, 0x7e, 0xcb, 0x01, 0xcc, 0x62, 0xe4, 0xf4, 0xfd, 0x59, 0x4a, 0xbd, 0xd3, 0xa3, 0xdc, 0x5e,
	0x3e, 0xca, 0x0a, 0xde, 0x25, 0xcb, 0xf3, 0x3e, 0x65, 0xee, 0x47, 0xab, 0xb7, 0x67, 0xaa, 0xb7,
	0x34, 0xea, 0xca, 0xdd, 0xa5, 0x79, 0x9a, 0x1f, 0x00, 0xe9, 0xbf, 0x75, 0x40, 0x9b, 0x8f, 0xdc,
	0x3f, 0xeb, 0x00, 0x85, 0x01, 0x90, 0x49, 0x5a, 0x74, 0x19, 0xf2, 0x6f, 0xe2, 0x29, 0x25, 0xe4,
	0x28, 0xff, 0x44, 0x1f, 0x40, 0xfd, 0xcc, 0x8d, 0x59, 0xe8, 0xbb, 0x43, 0x67, 0xe1, 0xb5, 0x73,
	0x23, 0x11, 0xf3, 0x21, 0xf5, 0xf8, 0x25, 0x7e, 0xe2, 0x86, 0xa1, 0x3f, 0x2d, 0xea, 0xf4, 0xe9,
	0x55, 0x9e, 0x49, 0x74, 0x4f, 0xf9, 0xa3, 0x00, 0x25, 0xe1, 0x87, 0xd7, 0xa0, 0x95, 0xa9, 0xc1,
	0xce, 0x5c, 0x12, 0x13, 0xd0, 0x8a, 0x0a, 0xcc, 0x38, 0xde, 0x5b, 0x64, 0xf3, 0x87, 0xab, 0x36,
	0xb7, 0x17, 0xa1, 0x73, 0x37, 0x44, 0x22, 0x5a, 0x55, 0xd2, 0xea, 0xbb, 0x0d, 0x5e, 0xcf, 0xde,
	0x4a, 0xf3, 0xea, 0x92, 0x66, 0xe9, 0x51, 0xf9, 0x59, 0xfa, 0x9f, 0x6a, 0x8c, 0x6e, 0x43, 0xc3,
	0x20, 0xb6, 0xf3, 0x8c, 0x0c, 0x0c, 0x4e, 0x96, 0x1d, 0xdd, 0xc4, 0x8e, 0x49, 0x49, 0x07, 0x5b,
	0x96, 0x9c, 0x57, 0x7e, 0xba, 0xe4, 0x5a, 0xef, 0x5f, 0x70, 0xed, 0xfb, 0xb0, 0x9d, 0xbc, 0x61,
	0x9d, 0xcc, 0x45, 0x70, 0x0b, 0x50, 0xaa, 0xd2, 0x06, 0x66, 0x4f, 0xef, 0xa8, 0x36, 0x96, 0x73,
	0xa8, 0x01, 0x37, 0x3b, 0x2a, 0xa5, 0x3a, 0xa6, 0x8b, 0x3b, 0xf2, 0x73, 0x3c, 0x54, 0x83, 0x6a,
	0x67, 0x18, 0x44, 0xc9, 0x03, 0x53, 0xf9, 0x55, 0x02, 0x98, 0x09, 0xae, 0x1b, 0xdf, 0x4b, 0x58,
	0xa6, 0x79, 0x94, 0xc3, 0xa5, 0xd2, 0x5c, 0x91, 0x2f, 0x09, 0x21, 0xa8, 0x1d, 0xa9, 0x3a, 0x4f,
	0x18, 0x75, 0x74, 0xc3, 0x1c, 0x70, 0x52, 0xd9, 0x82, 0x7a, 0x2a, 0x23, 0x03, 0x9b, 0x0b, 0xf3,
	0x8a, 0x0b, 0x15, 0xcb, 0x3f, 0x1d, 0x25, 0xd3, 0xf3, 0x04, 0x0a, 0x73, 0x24, 0xb9, 0xbb, 0xf0,
	0x78, 0x4e, 0x51, 0x4d, 0xc1, 0x8b, 0x02, 0xa8, 0x3c, 0x80, 0x82, 0x20, 0xb7, 0x12, 0x14, 0x0c,
	0x62, 0x70, 0x42, 0x2b, 0x42, 0x4e, 0x37, 0xa6, 0xef, 0x53, 0xc2, 0xfd, 0x2a, 0x3e, 0x94, 0xa7,
	0x9b, 0xf9, 0xe9, 0x9f, 0x66, 0x4e, 0xbf, 0xec, 0x62, 0xc5, 0xe1, 0x1f, 0x2f, 0x1d, 0x7e, 0x1b,
	0x36, 0x4d, 0x4c, 0xc5, 0xdd, 0x4b, 0x0c, 0x47, 0xc3, 0x06, 0xff, 0x7f, 0x22, 0x1d, 0x17, 0x85,
	0xb1, 0xa7, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x70, 0x7d, 0xb2, 0xaa, 0x9c, 0x0d, 0x00, 0x00,
}
